/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _homeIndexRouteImport } from './routes/__home/index'

const _homeIndexRoute = _homeIndexRouteImport.update({
  id: '/__home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof _homeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof _homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__home/': typeof _homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/__home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _homeIndexRoute: typeof _homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__home/': {
      id: '/__home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _homeIndexRoute: _homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
